/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as EquipmentRouteRouteImport } from './routes/equipment/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipmentIndexRouteImport } from './routes/equipment/index'
import { Route as UserpageUuidRouteImport } from './routes/userpage/$uuid'
import { Route as PostsAllRouteImport } from './routes/posts/all'
import { Route as PostPost_idRouteImport } from './routes/post/$post_id'
import { Route as PhotoPhoto_idRouteImport } from './routes/photo/$photo_id'
import { Route as MypageViewRouteImport } from './routes/mypage/$view'
import { Route as ExhibitionExhibition_idRouteImport } from './routes/exhibition/$exhibition_id'
import { Route as ExhibitPhotoExhibitPhoto_idRouteImport } from './routes/exhibitPhoto/$exhibitPhoto_id'
import { Route as EquipmentRentRouteImport } from './routes/equipment/rent'
import { Route as DocumentDoc_idRouteImport } from './routes/document/$doc_id'
import { Route as CommentsAllRouteImport } from './routes/comments/all'
import { Route as BoardBoard_idRouteImport } from './routes/board/$board_id'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AlbumAlbum_idRouteImport } from './routes/album/$album_id'
import { Route as AdminUserRouteImport } from './routes/admin/user'
import { Route as AboutAaaRouteImport } from './routes/about/$aaa'
import { Route as EquipmentAdminRouteRouteImport } from './routes/equipment/admin/route'
import { Route as EquipmentAdminIndexRouteImport } from './routes/equipment/admin/index'
import { Route as EquipmentAdminFeesRouteImport } from './routes/equipment/admin/fees'

const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRouteRoute = EquipmentRouteRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIndexRoute = EquipmentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EquipmentRouteRoute,
} as any)
const UserpageUuidRoute = UserpageUuidRouteImport.update({
  id: '/userpage/$uuid',
  path: '/userpage/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsAllRoute = PostsAllRouteImport.update({
  id: '/posts/all',
  path: '/posts/all',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPost_idRoute = PostPost_idRouteImport.update({
  id: '/post/$post_id',
  path: '/post/$post_id',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoPhoto_idRoute = PhotoPhoto_idRouteImport.update({
  id: '/photo/$photo_id',
  path: '/photo/$photo_id',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageViewRoute = MypageViewRouteImport.update({
  id: '/mypage/$view',
  path: '/mypage/$view',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionExhibition_idRoute = ExhibitionExhibition_idRouteImport.update({
  id: '/exhibition/$exhibition_id',
  path: '/exhibition/$exhibition_id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitPhotoExhibitPhoto_idRoute =
  ExhibitPhotoExhibitPhoto_idRouteImport.update({
    id: '/exhibitPhoto/$exhibitPhoto_id',
    path: '/exhibitPhoto/$exhibitPhoto_id',
    getParentRoute: () => rootRouteImport,
  } as any)
const EquipmentRentRoute = EquipmentRentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => EquipmentRouteRoute,
} as any)
const DocumentDoc_idRoute = DocumentDoc_idRouteImport.update({
  id: '/document/$doc_id',
  path: '/document/$doc_id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsAllRoute = CommentsAllRouteImport.update({
  id: '/comments/all',
  path: '/comments/all',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardBoard_idRoute = BoardBoard_idRouteImport.update({
  id: '/board/$board_id',
  path: '/board/$board_id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumAlbum_idRoute = AlbumAlbum_idRouteImport.update({
  id: '/album/$album_id',
  path: '/album/$album_id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserRoute = AdminUserRouteImport.update({
  id: '/admin/user',
  path: '/admin/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAaaRoute = AboutAaaRouteImport.update({
  id: '/about/$aaa',
  path: '/about/$aaa',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentAdminRouteRoute = EquipmentAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => EquipmentRouteRoute,
} as any)
const EquipmentAdminIndexRoute = EquipmentAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EquipmentAdminRouteRoute,
} as any)
const EquipmentAdminFeesRoute = EquipmentAdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => EquipmentAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRouteRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/equipment/admin': typeof EquipmentAdminRouteRouteWithChildren
  '/about/$aaa': typeof AboutAaaRoute
  '/admin/user': typeof AdminUserRoute
  '/album/$album_id': typeof AlbumAlbum_idRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/board/$board_id': typeof BoardBoard_idRoute
  '/comments/all': typeof CommentsAllRoute
  '/document/$doc_id': typeof DocumentDoc_idRoute
  '/equipment/rent': typeof EquipmentRentRoute
  '/exhibitPhoto/$exhibitPhoto_id': typeof ExhibitPhotoExhibitPhoto_idRoute
  '/exhibition/$exhibition_id': typeof ExhibitionExhibition_idRoute
  '/mypage/$view': typeof MypageViewRoute
  '/photo/$photo_id': typeof PhotoPhoto_idRoute
  '/post/$post_id': typeof PostPost_idRoute
  '/posts/all': typeof PostsAllRoute
  '/userpage/$uuid': typeof UserpageUuidRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/equipment/admin/fees': typeof EquipmentAdminFeesRoute
  '/equipment/admin/': typeof EquipmentAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/about/$aaa': typeof AboutAaaRoute
  '/admin/user': typeof AdminUserRoute
  '/album/$album_id': typeof AlbumAlbum_idRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/board/$board_id': typeof BoardBoard_idRoute
  '/comments/all': typeof CommentsAllRoute
  '/document/$doc_id': typeof DocumentDoc_idRoute
  '/equipment/rent': typeof EquipmentRentRoute
  '/exhibitPhoto/$exhibitPhoto_id': typeof ExhibitPhotoExhibitPhoto_idRoute
  '/exhibition/$exhibition_id': typeof ExhibitionExhibition_idRoute
  '/mypage/$view': typeof MypageViewRoute
  '/photo/$photo_id': typeof PhotoPhoto_idRoute
  '/post/$post_id': typeof PostPost_idRoute
  '/posts/all': typeof PostsAllRoute
  '/userpage/$uuid': typeof UserpageUuidRoute
  '/equipment': typeof EquipmentIndexRoute
  '/equipment/admin/fees': typeof EquipmentAdminFeesRoute
  '/equipment/admin': typeof EquipmentAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRouteRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/equipment/admin': typeof EquipmentAdminRouteRouteWithChildren
  '/about/$aaa': typeof AboutAaaRoute
  '/admin/user': typeof AdminUserRoute
  '/album/$album_id': typeof AlbumAlbum_idRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/board/$board_id': typeof BoardBoard_idRoute
  '/comments/all': typeof CommentsAllRoute
  '/document/$doc_id': typeof DocumentDoc_idRoute
  '/equipment/rent': typeof EquipmentRentRoute
  '/exhibitPhoto/$exhibitPhoto_id': typeof ExhibitPhotoExhibitPhoto_idRoute
  '/exhibition/$exhibition_id': typeof ExhibitionExhibition_idRoute
  '/mypage/$view': typeof MypageViewRoute
  '/photo/$photo_id': typeof PhotoPhoto_idRoute
  '/post/$post_id': typeof PostPost_idRoute
  '/posts/all': typeof PostsAllRoute
  '/userpage/$uuid': typeof UserpageUuidRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/equipment/admin/fees': typeof EquipmentAdminFeesRoute
  '/equipment/admin/': typeof EquipmentAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/equipment'
    | '/calculator'
    | '/equipment/admin'
    | '/about/$aaa'
    | '/admin/user'
    | '/album/$album_id'
    | '/auth/login'
    | '/auth/signup'
    | '/board/$board_id'
    | '/comments/all'
    | '/document/$doc_id'
    | '/equipment/rent'
    | '/exhibitPhoto/$exhibitPhoto_id'
    | '/exhibition/$exhibition_id'
    | '/mypage/$view'
    | '/photo/$photo_id'
    | '/post/$post_id'
    | '/posts/all'
    | '/userpage/$uuid'
    | '/equipment/'
    | '/equipment/admin/fees'
    | '/equipment/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/about/$aaa'
    | '/admin/user'
    | '/album/$album_id'
    | '/auth/login'
    | '/auth/signup'
    | '/board/$board_id'
    | '/comments/all'
    | '/document/$doc_id'
    | '/equipment/rent'
    | '/exhibitPhoto/$exhibitPhoto_id'
    | '/exhibition/$exhibition_id'
    | '/mypage/$view'
    | '/photo/$photo_id'
    | '/post/$post_id'
    | '/posts/all'
    | '/userpage/$uuid'
    | '/equipment'
    | '/equipment/admin/fees'
    | '/equipment/admin'
  id:
    | '__root__'
    | '/'
    | '/equipment'
    | '/calculator'
    | '/equipment/admin'
    | '/about/$aaa'
    | '/admin/user'
    | '/album/$album_id'
    | '/auth/login'
    | '/auth/signup'
    | '/board/$board_id'
    | '/comments/all'
    | '/document/$doc_id'
    | '/equipment/rent'
    | '/exhibitPhoto/$exhibitPhoto_id'
    | '/exhibition/$exhibition_id'
    | '/mypage/$view'
    | '/photo/$photo_id'
    | '/post/$post_id'
    | '/posts/all'
    | '/userpage/$uuid'
    | '/equipment/'
    | '/equipment/admin/fees'
    | '/equipment/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipmentRouteRoute: typeof EquipmentRouteRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  AboutAaaRoute: typeof AboutAaaRoute
  AdminUserRoute: typeof AdminUserRoute
  AlbumAlbum_idRoute: typeof AlbumAlbum_idRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BoardBoard_idRoute: typeof BoardBoard_idRoute
  CommentsAllRoute: typeof CommentsAllRoute
  DocumentDoc_idRoute: typeof DocumentDoc_idRoute
  ExhibitPhotoExhibitPhoto_idRoute: typeof ExhibitPhotoExhibitPhoto_idRoute
  ExhibitionExhibition_idRoute: typeof ExhibitionExhibition_idRoute
  MypageViewRoute: typeof MypageViewRoute
  PhotoPhoto_idRoute: typeof PhotoPhoto_idRoute
  PostPost_idRoute: typeof PostPost_idRoute
  PostsAllRoute: typeof PostsAllRoute
  UserpageUuidRoute: typeof UserpageUuidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/': {
      id: '/equipment/'
      path: '/'
      fullPath: '/equipment/'
      preLoaderRoute: typeof EquipmentIndexRouteImport
      parentRoute: typeof EquipmentRouteRoute
    }
    '/userpage/$uuid': {
      id: '/userpage/$uuid'
      path: '/userpage/$uuid'
      fullPath: '/userpage/$uuid'
      preLoaderRoute: typeof UserpageUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/all': {
      id: '/posts/all'
      path: '/posts/all'
      fullPath: '/posts/all'
      preLoaderRoute: typeof PostsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$post_id': {
      id: '/post/$post_id'
      path: '/post/$post_id'
      fullPath: '/post/$post_id'
      preLoaderRoute: typeof PostPost_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/$photo_id': {
      id: '/photo/$photo_id'
      path: '/photo/$photo_id'
      fullPath: '/photo/$photo_id'
      preLoaderRoute: typeof PhotoPhoto_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/$view': {
      id: '/mypage/$view'
      path: '/mypage/$view'
      fullPath: '/mypage/$view'
      preLoaderRoute: typeof MypageViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibition/$exhibition_id': {
      id: '/exhibition/$exhibition_id'
      path: '/exhibition/$exhibition_id'
      fullPath: '/exhibition/$exhibition_id'
      preLoaderRoute: typeof ExhibitionExhibition_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitPhoto/$exhibitPhoto_id': {
      id: '/exhibitPhoto/$exhibitPhoto_id'
      path: '/exhibitPhoto/$exhibitPhoto_id'
      fullPath: '/exhibitPhoto/$exhibitPhoto_id'
      preLoaderRoute: typeof ExhibitPhotoExhibitPhoto_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/rent': {
      id: '/equipment/rent'
      path: '/rent'
      fullPath: '/equipment/rent'
      preLoaderRoute: typeof EquipmentRentRouteImport
      parentRoute: typeof EquipmentRouteRoute
    }
    '/document/$doc_id': {
      id: '/document/$doc_id'
      path: '/document/$doc_id'
      fullPath: '/document/$doc_id'
      preLoaderRoute: typeof DocumentDoc_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments/all': {
      id: '/comments/all'
      path: '/comments/all'
      fullPath: '/comments/all'
      preLoaderRoute: typeof CommentsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$board_id': {
      id: '/board/$board_id'
      path: '/board/$board_id'
      fullPath: '/board/$board_id'
      preLoaderRoute: typeof BoardBoard_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$album_id': {
      id: '/album/$album_id'
      path: '/album/$album_id'
      fullPath: '/album/$album_id'
      preLoaderRoute: typeof AlbumAlbum_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user': {
      id: '/admin/user'
      path: '/admin/user'
      fullPath: '/admin/user'
      preLoaderRoute: typeof AdminUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/$aaa': {
      id: '/about/$aaa'
      path: '/about/$aaa'
      fullPath: '/about/$aaa'
      preLoaderRoute: typeof AboutAaaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/admin': {
      id: '/equipment/admin'
      path: '/admin'
      fullPath: '/equipment/admin'
      preLoaderRoute: typeof EquipmentAdminRouteRouteImport
      parentRoute: typeof EquipmentRouteRoute
    }
    '/equipment/admin/': {
      id: '/equipment/admin/'
      path: '/'
      fullPath: '/equipment/admin/'
      preLoaderRoute: typeof EquipmentAdminIndexRouteImport
      parentRoute: typeof EquipmentAdminRouteRoute
    }
    '/equipment/admin/fees': {
      id: '/equipment/admin/fees'
      path: '/fees'
      fullPath: '/equipment/admin/fees'
      preLoaderRoute: typeof EquipmentAdminFeesRouteImport
      parentRoute: typeof EquipmentAdminRouteRoute
    }
  }
}

interface EquipmentAdminRouteRouteChildren {
  EquipmentAdminFeesRoute: typeof EquipmentAdminFeesRoute
  EquipmentAdminIndexRoute: typeof EquipmentAdminIndexRoute
}

const EquipmentAdminRouteRouteChildren: EquipmentAdminRouteRouteChildren = {
  EquipmentAdminFeesRoute: EquipmentAdminFeesRoute,
  EquipmentAdminIndexRoute: EquipmentAdminIndexRoute,
}

const EquipmentAdminRouteRouteWithChildren =
  EquipmentAdminRouteRoute._addFileChildren(EquipmentAdminRouteRouteChildren)

interface EquipmentRouteRouteChildren {
  EquipmentAdminRouteRoute: typeof EquipmentAdminRouteRouteWithChildren
  EquipmentRentRoute: typeof EquipmentRentRoute
  EquipmentIndexRoute: typeof EquipmentIndexRoute
}

const EquipmentRouteRouteChildren: EquipmentRouteRouteChildren = {
  EquipmentAdminRouteRoute: EquipmentAdminRouteRouteWithChildren,
  EquipmentRentRoute: EquipmentRentRoute,
  EquipmentIndexRoute: EquipmentIndexRoute,
}

const EquipmentRouteRouteWithChildren = EquipmentRouteRoute._addFileChildren(
  EquipmentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipmentRouteRoute: EquipmentRouteRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  AboutAaaRoute: AboutAaaRoute,
  AdminUserRoute: AdminUserRoute,
  AlbumAlbum_idRoute: AlbumAlbum_idRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  BoardBoard_idRoute: BoardBoard_idRoute,
  CommentsAllRoute: CommentsAllRoute,
  DocumentDoc_idRoute: DocumentDoc_idRoute,
  ExhibitPhotoExhibitPhoto_idRoute: ExhibitPhotoExhibitPhoto_idRoute,
  ExhibitionExhibition_idRoute: ExhibitionExhibition_idRoute,
  MypageViewRoute: MypageViewRoute,
  PhotoPhoto_idRoute: PhotoPhoto_idRoute,
  PostPost_idRoute: PostPost_idRoute,
  PostsAllRoute: PostsAllRoute,
  UserpageUuidRoute: UserpageUuidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
