name: Deploy

on:
  push:
    branches:
      - feat/update-packages

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: yarn install --frozen-lockfile

      - run: yarn build:editor

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          preCommands: yarn build
          command: pages deploy build --project-name=snuaaa-web
          workingDirectory: packages/community
